### PR TITLE
js-http-client: add raw ipfs pubsub pub and sub from go-textile v0.7.6

### PR DESCRIPTION
**Pull request by flyskywhy**
Add raw ipfs pubsub pub and sub to [Expose simple p2p direct message API](https://github.com/textileio/go-textile/issues/885)

For easy PR review, there is no latest docs in this PR

Need PR [ipfs: add raw pubsub pub and sub to api and cmd and mobile](https://github.com/textileio/go-textile/pull/940) and set go-textile to v0.7.6 first

### CODE REVIEW

**Review by carsonfarmer — APPROVED** [review]
Thanks for this very details, very clean contribution. I'm inclined to just say, let's get this in and start testing it. It looks like the streaming/event-based work might be useful elsewhere, so excited to get this in a start playing around with it TBH.
I don't have any specific changes or requirements on this end. LGTM.

**Comment by carsonfarmer** [comment]
Once the required changes to the go-textile libs etc are done, let's merge this, submit a separate docs update PR, and then push out a new (minor bump) release.

**Comment by asutula** [comment]
@carsonfarmer the go-textile update is already out.

**Comment by flyskywhy** [comment]
I'm glad to be helpful on the great WEB3 project textile :laughing: 

Please push out a new release of js-http-client if possible, thanks!

**Comment by carsonfarmer** [comment]
Released!

**Pull request merged**
