### PR TITLE
Updates docs, bumps version

### PR DESCRIPTION
**Pull request by andrewxhill**
Okay! If we get this guy out I can go back and get that docs PR a bit closer

### CODE REVIEW

**Comment by carsonfarmer** [comment]
No need to bump versions here andrew. Just use `yarn release` instead.

**Comment by andrewxhill** [comment]
looks like `yarn release` => `yarn version --patch` which amounts to the same right?

**Comment by carsonfarmer** [comment]
Yup, same same, you just don't need to do it is all. Safer that way. More of a FYI I guess. It also automatically does the release and push.

**Comment by andrewxhill** [comment]
gotcha, cool

**Comment by andrewxhill** [comment]
good if i merge this guy and do the release then?

**Review by carsonfarmer — APPROVED** [review]
Cheers!

**Pull request merged**
